/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;

/**
 *
 * @author Geny
 */
public class ConfigTipos extends javax.swing.JDialog {
    ArrayList<InfoColumna> listaColumnas;
    
    /**
     * Creates new form ConfTipos
     * @param parent
     * @param modal
     * @param col
     * @param hoja
     */
    public ConfigTipos(java.awt.Frame parent, boolean modal, String hoja,ArrayList<InfoColumna> col) {
        super(parent, modal); 
        initComponents();
        setTitle("Configurar tipos de la columna " + hoja);     
        listaColumnas = col;
        jPanel2.setLayout(new FlowLayout(FlowLayout.CENTER));
        
        for(int i=0;i<listaColumnas.size();i++){
            jPanel2.add(new PanelColumna(listaColumnas.get(i),this,grupoUnique));
        }
        
        if(listaColumnas.size()<8){
            jScrollPane1.getVerticalScrollBar().setEnabled(false);
            jPanel1.setPreferredSize(new Dimension(580,0));
            jScrollPane1.setPreferredSize(new Dimension(0, ((34+4)*listaColumnas.size())+7));
            jPanel2.setPreferredSize(new Dimension(0,((34+4)*listaColumnas.size())+5));
            // ajustar el tamaño de la ventana al número de elementos cuando son menos de 8
            setPreferredSize(new Dimension(586,((34+4)*(listaColumnas.size()+1))-2));
        }else{
            jPanel1.setPreferredSize(new Dimension(596,0));// ancho del panel en donde está el jScrollPane
            jScrollPane1.setPreferredSize(new Dimension(0, 300)); // altura del jScrollpane
            jPanel2.setPreferredSize(new Dimension(0,((34+4)*listaColumnas.size())+5)); // altura del panel dentro del scroll
            // (34+4): alto del panel + separación entre cada panel
            setPreferredSize(new Dimension(602,329));
        } 
        setLocationRelativeTo(parent);
        pack();
        setResizable(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoUnique = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(530, 300));

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));

        jScrollPane1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        try {    
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.err.println(ex);
        }

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigTipos dialog = new ConfigTipos(new javax.swing.JFrame(), true, "hoja");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoUnique;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
