/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;

/**
 * JDialog en donde se muestran los objetos de la clase PanelColumna
 * que contienen la información para cada columna de la hoja seleccionada.
 * @author Geny
 * @version 1.0
 */
public class ConfigTipos extends javax.swing.JDialog {
    // Lista que contiene en cada elemento la información de una columna de la hoja actual
    private ArrayList<InfoColumna> listaColumnas;
    
    /**
     * Crea una nueva forma ConfTipos mostrando la información de cada columna de la
     * hoja actual y los campos que permiten modificar los atributos de la columna
     * @param parent Ventana padre desde la que se muestra la nueva ventana 
     * @param modal Especifica si el diálogo bloquea otras ventanas de nivel superior cuando se muestra. 
     * @param hoja  Nombre de la hoja actual
     * @param col   Lista de columnas en la hoja 
     */
    public ConfigTipos(java.awt.Frame parent, boolean modal, String hoja, ArrayList<InfoColumna> col) {
        super(parent, modal); 
        initComponents();
        setTitle("Configurar tipos de la columna " + hoja);     
        listaColumnas = col;
        panelInterno.setLayout(new FlowLayout(FlowLayout.CENTER));
        
        // Crear un nuevo panel con la información de cada columna y añadirlo al contenedor
        for(int i=0;i<listaColumnas.size();i++){
            panelInterno.add(new PanelColumna(listaColumnas.get(i),this,grupoUnique));
        }
        
        // Ajustar el tamaño de la ventana al número de elementos cuando son menos de 8
        if(listaColumnas.size()<8){
            jScrollPane1.getVerticalScrollBar().setEnabled(false);
            panelExterno.setPreferredSize(new Dimension(580, 0));
            jScrollPane1.setPreferredSize(new Dimension(0, ((34+4)*listaColumnas.size())+7));
            panelInterno.setPreferredSize(new Dimension(0, ((34+4)*listaColumnas.size())+5));  
            setPreferredSize(new Dimension(586,((34+4)*(listaColumnas.size()+1))-2));
        }else{
            panelExterno.setPreferredSize(new Dimension(596, 0)); // ancho del panel en donde está el jScrollPane
            jScrollPane1.setPreferredSize(new Dimension(0, 300)); // altura del jScrollpane
            // altura del panel dentro del scroll; (34+4): alto del panel + separación entre cada panel
            panelInterno.setPreferredSize(new Dimension(0, ((34+4)*listaColumnas.size())+5));
            setPreferredSize(new Dimension(602, 329));                      
        } 
        setLocationRelativeTo(parent);
        pack();
        setResizable(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoUnique = new javax.swing.ButtonGroup();
        panelExterno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelInterno = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(530, 300));

        panelExterno.setBackground(new java.awt.Color(255, 0, 102));

        jScrollPane1.setToolTipText("");

        panelInterno.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelInterno);

        javax.swing.GroupLayout panelExternoLayout = new javax.swing.GroupLayout(panelExterno);
        panelExterno.setLayout(panelExternoLayout);
        panelExternoLayout.setHorizontalGroup(
            panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        panelExternoLayout.setVerticalGroup(
            panelExternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExternoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoUnique;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelExterno;
    private javax.swing.JPanel panelInterno;
    // End of variables declaration//GEN-END:variables
}
